// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	models "github.com/StasikLeyshin/grpc-kafka-services/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockServerRepository is a mock of ServerRepository interface.
type MockServerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockServerRepositoryMockRecorder
}

// MockServerRepositoryMockRecorder is the mock recorder for MockServerRepository.
type MockServerRepositoryMockRecorder struct {
	mock *MockServerRepository
}

// NewMockServerRepository creates a new mock instance.
func NewMockServerRepository(ctrl *gomock.Controller) *MockServerRepository {
	mock := &MockServerRepository{ctrl: ctrl}
	mock.recorder = &MockServerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServerRepository) EXPECT() *MockServerRepositoryMockRecorder {
	return m.recorder
}

// CreateServer mocks base method.
func (m *MockServerRepository) CreateServer(server *models.Server, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateServer", server, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateServer indicates an expected call of CreateServer.
func (mr *MockServerRepositoryMockRecorder) CreateServer(server, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServer", reflect.TypeOf((*MockServerRepository)(nil).CreateServer), server, user)
}

// GetServer mocks base method.
func (m *MockServerRepository) GetServer(serverUuid string) (*models.Server, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServer", serverUuid)
	ret0, _ := ret[0].(*models.Server)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServer indicates an expected call of GetServer.
func (mr *MockServerRepositoryMockRecorder) GetServer(serverUuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServer", reflect.TypeOf((*MockServerRepository)(nil).GetServer), serverUuid)
}

// ServerAutoMigrate mocks base method.
func (m *MockServerRepository) ServerAutoMigrate() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServerAutoMigrate")
	ret0, _ := ret[0].(error)
	return ret0
}

// ServerAutoMigrate indicates an expected call of ServerAutoMigrate.
func (mr *MockServerRepositoryMockRecorder) ServerAutoMigrate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServerAutoMigrate", reflect.TypeOf((*MockServerRepository)(nil).ServerAutoMigrate))
}
